### ISSUE TITLE
Multiple Jobs - Concrete Example

### ISSUE THREAD

**Issue by ViertelGeviert25** [kc596/PriorityWorkerPool#1] opened 2021-03-23 20:49 UTC
Hi,

@kc596 First of all, thank you for this implementation. However, I have a problem in illustrating this issue: In the Quickstart, one job (with a random priority) is submitted to the pool. 

If I now have several jobs and would like to prioritize them using your approach, i.e.:

`	job1 := func() {
		fmt.Println("test1")
	}

	job2 := func() {
		fmt.Println("test2")
	}

	pool.Submit(job1, 1+10)
	pool.Submit(job2, 1+1)
`

However, I do not get any console output.... I expect because of a smaller number job 2 has a higher priority than job 1, so the result should always be "test2" and then "test1".

What should I do?

Thanks for considering my request!

**Comment by kc596** [comment] 2021-03-24 04:00
Hey @PhilemonWeber 

**priorityworkerpool** aim is to control the number of go routines in the system and run the higher priority job first. 

However, it should be noted that it is not preemptive - if a lower priority job is already scheduled (picked up), higher priority job won't stop the first job. Among all the already submitted jobs, highest priority job will be scheduled first.

Coming to your issue, all the jobs are run in go routines so your go runtime is not waiting for them. You need to wait for the jobs to finish.

Here's the complete example:

```go
package main

import (
	"fmt"
	"github.com/kc596/priorityworkerpool"
	"time"
)

const (
	poolName   = "singleWorkerPool"
	numWorkers = 1  // Just one worker
)

var panicHandler = func(alias string, err interface{}) {
	fmt.Println(alias, err)
}

func main() {
	pool := priorityworkerpool.New(poolName, numWorkers, panicHandler)

	// Just sleep for sometime and block the worker pool
	job1 := func() {
		fmt.Println("Job 1 - start")
		time.Sleep(1 * time.Second)
		fmt.Println("Job 1 - end")
	}

	job2 := func() {
		fmt.Println("Job 2")
	}

	job3 := func() {
		fmt.Println("Job 3")
	}

	pool.Submit(job1, 1)
	pool.Submit(job2, 500)
	pool.Submit(job3, 501)

	pool.WaitGroup().Wait()
}

/**
Output:
	
Job 3
Job 2
Job 1 - start
Job 1 - end
*/
```

**NOTE:** Just for this example, I have used a pool with just 1 worker. Please edit it according to your requirement.

**Comment by kc596** [comment] 2021-03-31 06:23
Closing since the problem is resolved.

Reopen if not the case.

**Closed as completed by kc596** 2021-03-31 06:23 UTC
